---
title: "Seurat data subsetting & exp level graph"
author: "Shay Iyer"
date: "5/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sleepwalk)
library(SCINA)
library(R.utils)
library(monocle3)
require(monocle3)
require(Seurat)
require(data.table)
theme_set(theme_bw(base_size=14))
```

```{r}
all <- readRDS("~/Desktop/Computational-Group/Farnsworth_2019.rds")
```

```{r}
all <- UpdateSeuratObject(all)
```

```{r}
all[["ClusterNames"]] <- Idents(object=all)
current.cluster.ids <- c(0:220)
# below list corresponds to the "Ident Annotation" column of the table Table S2
new.cluster.ids <- c("Peri1a", "RetProgAlla", "MHBDiff12a", "NonspecificAlla", "MHBProg12", "Gill5a", "RBC2a", "MusSkelFast1", "HBProg1a", "MusSkelFast2a", "FBProgAlla", "MBDiff5", "MBProg12a", "MHBNeur25", "HBProg1b", "SCProg12a", "Arch2a", "antSCProg1a", "NCcart2", "HBProg1c", "antSCDiff12a", "Gill5b", "Myotome", "Basal5a", "NCcranial5a", "FBNeurInhibAll", "HBDiff1a", "MHBNeurGlutAll", "Parachord12", "NCcranial5b", "RetDiff2", "NCcranial2", "NCcranial1a", "Sclero1", "RetProg1a", "SCNeurCilia12a", "MusSkelProgAll", "RetDiff25a", "RBC1a", "SCProg12b", "FMBProgAll", "MHBProgAll", "MBDiff25", "HBProg1d", "MyoProg5a", "PharEpi1a", "PharEpi1b", "Basal2a", "RBC2b", "Nonspecific12", "NCcart5a", "HBDiff12a", "RetProg0a", "MyoProg5b", "RetProg0b", "Hepato5a", "CranGangAlla", "MusSkelSlow1a", "RetDiffAll", 
"Thymus", "RetDiff25b", "HBProgMN1e", "FBProgAllb", "RBC1b", "NCneural12", "antSCDiff12b", "HBDiff12b", "FloorplateMB1", "FMBDiff12a", "NCcardiac", "Basal1", "Macro5", "MHBDiff25", "RetNeuron25", "RetProgAllb", "HBDiff25", "MHBNeurGABAAll", "Peri2a", "Peri2b", "EndotheAlla", "NCcranial5e", "BasalFin5a", "HBDiff12c", "RetDiff25c", "MyoProg2a", "RBC2c", "MHBDiff12b", "NCcranial1b", "EndotheAllb", "FBProgAllc", "OligoFB", "FBProgAlld", "Sclero2", "Otic", "Olfactory", "SCDiff12a", "RPE", "RadialGlia2", "FinBud12", "RetProgAllc", "MesenUnk2", "IntestineEpiAll", "NCcranial1c", "MusSkelFast2b", "RetDiff25d", "CranGangAllb", "LensEpi", "RetDiff2", "BasalFin1", "RadialGlia5", "FinBud25", "MBProg12b", "SCNeurInhib12a", "RetDiff25e", "antSCProg1b", "RetPR", "MusSkelSlow25", "Vessel1", "Basal12", 
"HG1", "HBProg12", "Hepato5b", "RetProg5a", "SCDiff2", "FMBDiff12b", "FinBud5", "HBDiffMN12d", "MyoProg2b", "IonoNaK", "NCirid", "HeartTube", "HBDIff1b", "OligoFMB", "IonoNCC5a", "FBProg12", "MesenUnk5", "MHBNeurGABA12", "LatLine", "RetDiff25f", "HBDiff1c", "Arch12", "LensAll", "FBDiffAll", "SCNeurMN12b", "Kidney", "BasalFin12", "Gill5c", "HeartPrimord", "NCcart5b", "Notochord25", "Neutrophil", "MHBDiff1", "IntestineEpi5a", "RBCProgAll", "MusCeph", "Tailbud", "NCxantho1", "RBC5", "Notochord1", "NonspecificAll", "SCDiff12c", "NCcranial1d", "Spleen", "Roofplate", "NCcranial1e", "IonoNCC5b", "antSCProg1c", "Vessel2", "IntestineEpi5b", "MucNCC", "NCcranial5c", "MusVascSmo", "HBDiff2", "NCneural25", "NCmel1", "PlacodalUnk", "FloorplateSCAll", "RetNeuron5", "NCmel25", 
"PharEpi2", "PancExo", "NCcranial5d", "Peri2c", "Peri1b", "Macro12", "NCxantho25", "Basal5b", "Nonspecific1a", "BasalFin5b", "PancAB", "Peri1c", "Parachord1", "FBDiff12", "Nonspecific1b", "SCDiff12c", "MHBProg1", "TasteBud", "MusEntSmo", "HairCell", "Hypophysis", "Lens12", "Vessel5", "SCNeurCilia12b", "Arch2b", "FinBud2", "MusCard", "Basal2b", "HG2", "IonovH", "MusSkelSlow1b", "SpleenEpi", "Epiphysis", "Macro1", "Endothe1", "IntestineEpi1", "Peri1d", "Osteo", "Hepato5c", "Hypochord", "PGC", "Nonspecific")
```

```{r}
all <- UpdateSeuratObject(all)
```

```{r}
#Switch to cluster name IDs 
Idents(all) <- plyr::mapvalues(x = Idents(all), from = current.cluster.ids, to = new.cluster.ids)
Idents(all)
```

```{r}
#Plot the umap of everything! yay!
DimPlot(object = all, reduction = "umap")
```


```{r}
nccranial_all <- c("NCcranial1a", "NCcranial1b", "NCcranial1c", "NCcranial1d", "NCcranial1e", "NCcranial2", "NCcranial5a", "NCcranial5b", "NCcranial5c", "NCcranial5d", "NCcranial5e", "NCneural12", "NCneural25")
```

```{r}
nccranials <- subset(x = all, idents = nccranial_all)
```

```{r}
RidgePlot(object = nccranials, feature = "metrnla") + labs(title = "Meteorin-like-a (metrnla) in Cranial Neural Crest populations", subtitle = "Cell populations as defined by Farnsworth et al., 2019")
```

```{r}
RidgePlot(object = nccranials, feature = "metrn") + labs(title = "Meteorin (metrn) in Cranial Neural Crest populations", subtitle = "Cell populations as defined by Farnsworth et al., 2019")
```

UMAP of all cells colored by timepoint
```{r}
DimPlot(object = all, reduction = "umap", group.by = "sample_name", pt.size = 0.1)
```

```{r}
sample1 <- "1_olig2_24a"
sample2 <- "2_olig2_24b"
sample3 <- "3_olig2_48a"
sample4 <- "4_elav_48b"
sample5 <- "5_olig2120a"
sample6 <- "6_olig2120b"

all1a <- subset(x=all, subset = sample_name==sample1)
all1b <- subset(x=all, subset = sample_name==sample2)
all2a <- subset(x=all, subset = sample_name==sample3)
all2b <- subset(x=all, subset = sample_name==sample4)
all5a <- subset(x=all, subset = sample_name==sample5)
all5b <- subset(x=all, subset = sample_name==sample6)
all1 <- merge(all1a, all1b)
all2 <- merge(all2a, all2b)
all5 <- merge(all5a, all5b)

#cleaning up environment
rm(all1a, all1b, all2a, all2b, all5a, all5b)
```

```{r}
#set identities to sample_name
Idents(all) <- "sample_name"
Idents(all)
```

```{r}
#set identities to Cluster name (number)

Idents(all) <- "ClusterNames"
Idents(all)
```

```{r}
#Maps cluster number to cluster name 
Idents(all) <- plyr::mapvalues(x = Idents(all), from = current.cluster.ids, to = new.cluster.ids)
Idents(all)
```

```{r}
current.sample_names <- c(sample1, sample2, sample3, sample4, sample5, sample6)
new.sample.names <- c(1, 1, 2, 2, 5, 5)

all@meta.data$sample_id <- plyr::mapvalues (x = all@meta.data$sample_name, from = current.sample_names, to = new.sample.names)
```

```{r}
DimPlot(object = all, reduction = "umap", group.by = "sample_id", pt.size = 0.1)
```



